export const APP_CONSTANTS = {
  ALCHEMY_KEY: process.env.REACT_APP_ALCHEMY_KEY,
  CONTRACT_ADDRESS: process.env.REACT_APP_CONTRACT_ADDRESS,
  OPENSEA_ASSETS_URL: process.env.REACT_APP_OPENSEA_ASSETS_URL,
  CLIENT_ID: process.env.REACT_APP_CLIENT_ID,
  RPC_TARGET: process.env.REACT_APP_RPC_TARGET,
  APP_LOGO: process.env.REACT_APP_APP_LOGO,
  ADAPTER_TWITTER_CLIENT_VERIFIER:
    process.env.REACT_APP_ADAPTER_TWITTER_CLIENT_VERIFIER,
  ADAPTER_TWITTER_CLIENT_ID: process.env.REACT_APP_TER_TWITTER_CLIENT_ID,
  AUTH0_DOMAIN: process.env.REACT_APP_AUTH0_DOMAIN,
  BIRD_IMAGE: process.env.REACT_APP_BIRD_IMAGE,
  REACT_APP_REFRESH_TIMER: process.env.REACT_APP_REACT_APP_REFRESH_TIMER,
};
